"""Add breed

Revision ID: c9b292683ac8
Revises: e6c72d8fee72
Create Date: 2024-10-01 18:40:23.619892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b292683ac8'
down_revision: Union[str, None] = 'e6c72d8fee72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('breed', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'breed')
    # ### end Alembic commands ###
